firenado/core/management/templates/init/__init__.py.txt

Fixed bad syntax on the app component template.

---

firenado/conf.py
firenado/core/__init__.py
firenado/core/management/templates/project/firenado.yaml.txt
firenado/core/session.py

Now an application may be defined with an application module on the config file.
Introduced a method to delete a key from session.
Fixed session clear method, forcing it to be persisted during the session write procedure.

Application has an application module right now. Session fixed.

---

.gitignore
firenado/examples/skell/__init__.py
firenado/examples/skell/bower.json
firenado/examples/skell/conf/firenado.yaml
firenado/examples/skell/handlers.py
firenado/examples/skell/templates/base.html
firenado/examples/skell/templates/index.html
firenado/examples/skell/templates/session.html

Introduced bower and templates to the skell application.
Session is handling values correctly and resetting(deleting a value by key) a persisted value.

Skell app is using bower, templates and session.

---

firenado/core/__init__.py
firenado/core/websocket.py
firenado/examples/chatdemo/__init__.py
firenado/examples/chatdemo/conf/firenado.yaml
firenado/examples/chatdemo/handlers.py
firenado/examples/chatdemo/static/chat.css
firenado/examples/chatdemo/static/chat.js
firenado/examples/chatdemo/templates/index.html
firenado/examples/chatdemo/templates/message.html
firenado/examples/chatdemows/__init__.py
firenado/examples/chatdemows/conf/firenado.yaml
firenado/examples/chatdemows/handlers.py
firenado/examples/chatdemows/static/chat.css
firenado/examples/chatdemows/static/chat.js
firenado/examples/chatdemows/templates/index.html
firenado/examples/chatdemows/templates/message.html

Introduced the websocket handler but it is necessary to refactor this code later.

Introduced websocket handler

---

firenado/core/__init__.py
firenado/core/management/tasks/__init__.py

Implemented the application gracefull shutdown.

---

firenado/conf.py
firenado/core/service.py
firenado/examples/chatdemows/handlers.py

The initial service layer was introduced to the codebase.
Fixed a session bug when the cookie was deleted on the client side and the next request generated a new session with id None.

Service layer introduced to the codebase

---

firenado/components/firenado/__init__.py
firenado/components/firenado/handlers.py
firenado/components/firenado/templates/info.html

Grabbed the info component from iFlux and moved to source code.
Refs: #48

Introduced the application info component.

---

firenado/__init__.py
firenado/examples/skell/conf/firenado.yaml
requirements.txt
setup.py

Started 0.1.1 on the develop branch.

Kicking 0.1.1

---

.travis.yml

Introduced travis to the project.

---

.travis.yml
firenado/conf.py
firenado/core/__init__.py
firenado/core/data/__init__.py
firenado/core/management/__init__.py
firenado/core/management/tasks/__init__.py
firenado/core/session.py
firenado/util/__init__.py
requirements.txt

Travis and skell app running on python 3

---

.travis.yml
README.md
firenado/core/security.py
setup.py

Also added more insight on the readme.md and introduced the core.security to the framework.

Fixed setup.py

---

docs/releases/v0.1.2.rst
firenado/components/assets/__init__.py
firenado/components/assets/conf/assets.yaml.example
firenado/examples/skell/conf/assets.yaml

Added root path to the assets component.

---

.travis.yml
MANIFEST.in
docs/releases.rst
docs/releases/v0.1.5.0.rst
docs/releases/v0.1.5.rst
firenado/__init__.py
firenado/data.py
setup.py

Closing release.
Fixes: #122 #124

Closing 0.1.5.0.

---

firenado/__init__.py
setup.py

Fixed emails and long description regarding the pypi legacy api.

Bump firenado to deliver 0.1.6 to master.

---

docs/releases.rst
docs/releases/v0.1.6.1.rst
docs/releases/v0.1.6.2.rst
firenado/__init__.py
setup.py

Delivering 0.1.6.2.

---

.travis.yml
docs/releases.rst
docs/releases/v0.1.7.0.rst
firenado/util/__init__.py
requirements/basic.txt
requirements/sqlalchemy.txt

Also removed python 3.3 from tests and added 0.1.7.0 documentation template.

Updated tornado and sqlalchemy

---

firenado/tornadoweb.py

Fix syntax warning over comparison of literals using is.

---

examples/testapp/management/commands.py
firenado/__init__.py
firenado/conf/__init__.py
firenado/config.py
firenado/data.py
firenado/launcher.py
firenado/management/management.py
firenado/management/tasks.py
firenado/schedule.py
firenado/security.py
firenado/service.py
firenado/session.py
firenado/tornadoweb.py
firenado/uimodules.py
requirements/basic.txt
requirements/sqlalchemy.txt
tests/__init__.py
tests/components_test.py
tests/conf_test.py
tests/config_test.py
tests/runtests.py
tests/security_test.py
tests/service_test.py
tests/session_test.py
tests/tornadoweb_test.py
tests/util/sqlalchemy_util_test.py
tests/util/url_util_test.py

We don't use six directly with this change but some decencies from the project may use it.
Logic is straight Python 3.

Removed six from the project

---

examples/schedapp/conf/firenado.yml
examples/testapp/app.py
firenado/conf/__init__.py
firenado/config.py
firenado/data.py
firenado/schedule.py
firenado/session.py
firenado/tornadoweb.py
requirements/tests.txt
tests/data_test.py
tests/runtests.py

This pull request will fix the majority of issues in 0.2.8.

Majority of fixes from 0.2.8.

---

firenado/conf/__init__.py
firenado/config.py
firenado/launcher.py
requirements/basic.txt
requirements/development.txt
requirements/redis.txt
requirements/schedule.txt
requirements/sqlalchemy.txt

Also changed logging configuration execution to the launcher.

Updated dependencies and used log_level_from_string from carcara.

---

docs/.readthedocs.yaml
requirements/docs.txt

This to inform readthedocs we need myst_parser to be installed
for our build.
Refs: #201

Added readthedocs configuration file.

---

README.md
docs/releases.rst
docs/releases/v0.2.16.md

Also changing the download link to go directly to the list of files
to be downloaded.
Refs: #390

Testing a markdown document.

---

README.md
examples/launcher/app.py
firenado/launcher.py
firenado/util/testing.py

Also delivered ProcessLauncher based test case.

ProcessLauncher without gen.coroutine.
